language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1

addons:
  sonarcloud:
    organization: "kuester"
    token:
      secure: '$SONAR_TOKEN'

script:
  - dotnet restore ".\SOLID_DesignPrinciplesDemo.sln"

jobs:
  include:
    - stage: Build
      script:
        - dotnet build ".\SOLID_DesignPrinciplesDemo.sln" -c Release

    - stage: Tests
      script:
        - dotnet test ".\SOLID_DesignPrinciplesDemo.sln" -c Release -v n
